id: A98816B1F
base_file: f657F.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:21:36.951095
  last_modified_at: 2022-06-17 11:21:36.951098
