id: A98816B1F
base_file: f4B6E.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:21:36.942189
  last_modified_at: 2022-06-17 11:21:36.942196
