id: A98816B1F
base_file: f8713.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:21:36.958818
  last_modified_at: 2022-06-17 11:21:36.958821
