id: A98816B1F
base_file: fF881.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:21:36.967703
  last_modified_at: 2022-06-17 11:21:36.967705
