id: A98816B1F
base_file: fC05C.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:21:36.966027
  last_modified_at: 2022-06-17 11:21:36.966030
