id: A98816B1F
base_file: f9DE4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:21:36.962523
  last_modified_at: 2022-06-17 11:21:36.962526
