id: A98816B1F
base_file: f50DE.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:21:36.945750
  last_modified_at: 2022-06-17 11:21:36.945753
