id: A98816B1F
base_file: f13E8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:21:36.925897
  last_modified_at: 2022-06-17 11:21:36.925910
